sprint 06
LobovVit/MovieQuiz pull request #4
Opened 2024-08-26 21:23 UTC by LobovVit

sprint 06

2024-08-27 09:29 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactory.swift
> +//                     correctAnswer: false),
Было бы хорошо лишние строки кода удалять, если они уже не используются. [Про проблемы лишних строк кода можно найти информацию в этой статье](https://habr.com/ru/articles/354750/)

2024-08-27 09:38 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactoryDelegate.swift
> +    func didFailToLoadData(with error: Error) // сообщение об ошибке загрузки
Документирование кода – это важная и полезная практика, но лучше избегать комментариев, если их смысл уже выражен через название функции или переменной. Как писал Роберт Мартин, хороший код должен быть самодокументируемым, чтобы его было легко понять без лишних пояснений, но если это не получается, то хорошо было бы добавить комментарий. [Ссылка на статью про комментирование кода](https://habr.com/ru/companies/piter/articles/458990/)

2024-08-27 09:39 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactory.swift
> +    init(moviesLoader: MoviesLoading,delegate: QuestionFactoryDelegate) {
У типа `MoviesLoading` после запятой стоит поставить пробел

2024-08-27 09:40 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        //questionFactory?.requestNextQuestion()
Стоит удалить строчку кода

2024-08-27 09:41 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet private weak var activityIndicator: UIActivityIndicatorView!
`activityIndicator` было бы хорошо поставить цвет, который отличается от стандартного, чтобы его лучше стало видно, так как на белом он мало-заметен.

2024-08-27 09:42 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.questionFactory = QuestionFactory(moviesLoader: MoviesLoader(),delegate: self)
Стоит поставить пробел после запятой у `MoviesLoader()`

2024-08-27 09:46 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                               buttonText: "Попробовать еще раз") { [weak self] in
Отступы на этом примере стоит использовать таким видом:
```swift
let model = AlertModel(
    title: "Ошибка",
    message: message,
    buttonText: "Попробовать еще раз"
) {
    ...
}
```
Это позволит быстрее добавить новый параметр, если модель была изменена, также это позволяет легче читать данный код и он выглядит более чистым

2024-08-27 09:51 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            guard let self = self else { return }
В последних версиях Swift появилась удобная возможность упростить развертывание опционала, если название переменной совпадает с тем, что мы хотим использовать без опционала.

Ранее для этого использовалась конструкция:
```swift
guard let self = self else { return }
```

Теперь её можно сократить и сделать код более читаемым:

```swift
guard let self else { return }
```

2024-08-27 09:51 UTC, Kirchberg commented on MovieQuiz/Models/MostPopularMovies.swift
> +        }
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-08-27 09:51 UTC, Kirchberg commented on MovieQuiz/Models/MostPopularMovies.swift
> +    }
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-08-27 09:58 UTC, Kirchberg commented on MovieQuiz/Models/MostPopularMovies.swift
> +    }
Для более лучшей читаемости кода могу предложить следующую организацию модели:
```swift
struct MostPopularMovies: Codable {
    let errorMessage: String
    let items: [Item] // Здесь мы переименовали структуру в Item
}

extension MostPopularMovies {

    struct Item: Codable {
        let title: String
        ...
        
    }

}
```
Переименование структуры `MostPopularMovie` в `Item` делает код более лаконичным и универсальным. Использование понятных и простых названий улучшает читаемость и делает структуру гибче для возможного расширения.
Размещение структуры `Item` внутри `MostPopularMovies` через `extension` лучше отражает семантику данных: Item является частью списка популярных фильмов.
Благодаря вложенности в `extension`, структура `Item` становится тесно связанной с контекстом, к которому она относится, что упрощает поддержку кода

2024-08-27 09:59 UTC, Kirchberg commented on MovieQuiz/Services/MoviesLoader.swift
> +    // MARK: - NetworkClient
После и до `MARK` стоит оставить одну пустую строку

2024-08-27 10:00 UTC, Kirchberg commented on MovieQuiz/Services/MoviesLoader.swift
> +        }
Было бы хорошо поправить отступы

2024-08-27 10:02 UTC, Kirchberg commented on MovieQuiz/Services/MoviesLoader.swift
> +            guard let url = URL(string: "https://tv-api.com/en/API/Top250Movies/k_zcuw1ytf") else {
URL лучше вынести в константу, чтобы он был легко доступен и изменяем. Например можно было бы сделать отдельный `enum` с именем `Constants` внутри `MoviesLoader`
```swift
private enum Constants {
    static let mostPopularMoviesUrlString = "https://tv-api.com/en/API/Top250Movies/k_zcuw1ytf"
}
```

2024-08-27 10:14 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactory.swift
> +                imageData = try Data(contentsOf: movie.resizedImageURL)
Использование `Data(contentsOf:)` для загрузки изображений синхронно в глобальной очереди может замедлить работу и вызвать проблемы с производительностью, особенно если изображения большие. [Подробная статья с описанием проблемы](https://medium.com/@parepalli46/how-not-to-use-data-contentsof-url-in-swift-3547488b09ec)

Изображение стоит получать через `URLSession.shared.dataTask(with: url)`, можно сделать отдельный метод, который принимает `URL` и через `completion` c типом `Data?` возвращает полученное изображение. Таким образом, мы можем избавиться от `DispatchQueue.global().async` и сделать код более асинхронным, быстрым и чистым

2024-08-27 10:20 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Обращу внимание, что игра состоит из вопроса о рейтинге, на который отвечает пользователь, и контекста о фильме в виде постера(картинка). 
Без постера, пользователю будет затруднительно ответить на вопрос о рейтинге фильма верно.

В этом месте, функция не завершает свою работу и идет формировать вопрос без постера. 
В таком случае, бизнес-логика приложения будет нарушена, потому что пользователь не сможет ответить корректно, ведь изображения нет.
Это состояние стоит обработать, например, с помощью алерта. 
Не забудь, что алерт будет обновлять UI и это тоже нужно учесть (вернуть на main), ровно также, как и прерывание функции (сделать return)

2024-08-27 10:21 UTC, Kirchberg commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Обращу внимание на свойство `errorMessage`. 

Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов `items`. 
С пустым списком приложение будет выглядеть сломанным. 
Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.
С точки зрения проектирования API сервиса IMDB, 
эту ошибку разработчики должны были вернуть c кодом ошибки клиента ([группа 4хх](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)). 
Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. 
Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).

 **Примеры состояний, когда такое происходит:**

- API key неверный
- API key просрочен
- количество запросов в день превышено (по документации не больше 100)

2024-08-27 10:25 UTC, Kirchberg requested changes
Привет, Виталий! Спасибо за работу, есть один критический комментарий, который нужно поправить, остальное для размышлений или предложение улучшений, отличная работа!

2024-08-27 19:53 UTC, LobovVit commented on MovieQuiz/Services/QuestionFactory.swift
> +//                     correctAnswer: false),
Убрал

2024-08-27 19:54 UTC, LobovVit commented on MovieQuiz/Services/QuestionFactoryDelegate.swift
> +    func didFailToLoadData(with error: Error) // сообщение об ошибке загрузки
Убрал

2024-08-27 19:55 UTC, LobovVit commented on MovieQuiz/Services/QuestionFactory.swift
> +    init(moviesLoader: MoviesLoading,delegate: QuestionFactoryDelegate) {
поправил

2024-08-27 19:55 UTC, LobovVit commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        //questionFactory?.requestNextQuestion()
почистил

2024-08-27 19:56 UTC, LobovVit commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.questionFactory = QuestionFactory(moviesLoader: MoviesLoader(),delegate: self)
поправил

2024-08-27 19:57 UTC, LobovVit commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                               buttonText: "Попробовать еще раз") { [weak self] in
поправил

2024-08-27 19:57 UTC, LobovVit commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            guard let self = self else { return }
поправил

2024-08-27 19:58 UTC, LobovVit commented on MovieQuiz/Models/MostPopularMovies.swift
> +    }
поправил

2024-08-27 20:01 UTC, LobovVit commented on MovieQuiz/Models/MostPopularMovies.swift
> +    }
спасибо за интересный подход!!! - подправил

2024-08-27 20:02 UTC, LobovVit commented on MovieQuiz/Services/MoviesLoader.swift
> +    // MARK: - NetworkClient
поправил

2024-08-27 20:03 UTC, LobovVit commented on MovieQuiz/Services/MoviesLoader.swift
> +        }
поправил

2024-08-27 20:08 UTC, LobovVit commented on MovieQuiz/Services/MoviesLoader.swift
> +            guard let url = URL(string: "https://tv-api.com/en/API/Top250Movies/k_zcuw1ytf") else {
поправил

2024-08-28 10:56 UTC, LobovVit commented on MovieQuiz/Services/QuestionFactory.swift
> +                imageData = try Data(contentsOf: movie.resizedImageURL)
поправил

2024-08-28 11:28 UTC, LobovVit commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
поправил в (loadMovies)

2024-08-28 13:06 UTC, Kirchberg commented on MovieQuiz/Services/MoviesLoader.swift
> +                        }
Стоит выделить данный enum за пределы функции `loadMovies` и дать осознанное название, например, `MoviesLoaderError`, то есть:
```swift
...
private let networkClient = NetworkClient()
...
enum MoviesLoaderError: Error {
    case emptyItems(String)
}
...
func loadMovies(handler: @escaping (Result<MostPopularMovies, Error>) -> Void) {
    ...
    handler(.failure(MoviesLoaderError.emptyItems(mostPopularMovies.errorMessage)))
    ...
}
```

Как критическое замечание не выделяю, но стоит поправить

2024-08-28 13:13 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactory.swift
> +            imageData = recievedData
Данные строчки кода не нужны, так как `receivedData` можно сразу передать в `QuizQuestion(image: ...,)`

2024-08-28 13:15 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactory.swift
> +            let qestionRating = Int.random(in: 6..<10)
Опечатка в названии переменной, `qestionRating` было бы хорошо переименовать в `questionRating`

2024-08-28 13:17 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactory.swift
> +            guard let recievedData = data, error == nil  else {
Опечатка в названии переменной, было бы хорошо переименовать `recievedData` в `receivedData`. Чтобы видеть, что грамматика слов неверна или допущены ошибки, можно включить проверку внутри Xcode.

<img width="993" alt="image" src="https://github.com/user-attachments/assets/276a5fcb-bb20-484f-a838-f85f6a579e86">

2024-08-28 13:18 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactory.swift
> +        guard let movie = self.movies[safe: index] else { return }
Можно упростить выбор фильма, если написать такую конструкцию:
```swift
guard let movie = movies.randomElement() else { 
    return
}
```

2024-08-28 13:22 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactory.swift
> +            let text = "Рейтинг этого фильма больше чем \(qestionRating)?"
Было бы хорошо еще сделать квиз с изменяемым больше/меньше вариантами. 

Классно, что ты сделал на рейтинг фильма, его диапазон также стоит сделать от 2 до 9 ✨

2024-08-28 13:26 UTC, Kirchberg approved these changes
Спасибо большое за исправления не только критических комментариев, но и добавление предложений для улучшений! Отличная работа, из того, что хотелось бы исправить остается в комментарии к `MoviesLoader`, остальное также для размышлений и улучшений

Approve ✨

2024-08-31 19:10 UTC, LobovVit commented on MovieQuiz/Services/MoviesLoader.swift
> +                        }
поправил

2024-08-31 19:11 UTC, LobovVit commented on MovieQuiz/Services/QuestionFactory.swift
> +            imageData = recievedData
поправил

2024-08-31 19:12 UTC, LobovVit commented on MovieQuiz/Services/QuestionFactory.swift
> +            let qestionRating = Int.random(in: 6..<10)
поправил

2024-08-31 19:12 UTC, LobovVit commented on MovieQuiz/Services/QuestionFactory.swift
> +            guard let recievedData = data, error == nil  else {
поправил

2024-08-31 19:14 UTC, LobovVit commented on MovieQuiz/Services/QuestionFactory.swift
> +        guard let movie = self.movies[safe: index] else { return }
поправил

2024-08-31 19:19 UTC, LobovVit commented on MovieQuiz/Services/QuestionFactory.swift
> +            let text = "Рейтинг этого фильма больше чем \(qestionRating)?"
поправил

2024-08-31 19:21 UTC, merged